services:

  app:
    build:
      context: ..
      dockerfile: ci-cd/Dockerfile
    ports:
      - '8080:8080'
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ../app:/usr/src/app