services:

  app:
    build:
      context: ..
      dockerfile: ci-cd/Dockerfile
    ports:
      - '5000:5000'
    restart: unless-stopped
    environment:
      - PYTHONUNBUFFERED=1
    volumes:
      - ../app:/usr/src/app